### ISSUE TITLE
Varistor size

### ISSUE THREAD

**Issue by jns-r** [stnkl/OpenIoTSwitch#1]
Hey there,

after building the switch, I noticed the varistor might be too weak.

![MOV-07D271 datasheet](https://user-images.githubusercontent.com/79789422/210129718-22099a31-7214-45bd-aa36-b9a3b6820602.png)

This is the recommended application circuit from Hi-Link
(https://www.hlktech.com/en/Goods-12.html)

![Hi-Link PM01 typical circuit](https://user-images.githubusercontent.com/79789422/210129755-9ff414c1-3766-4fbf-af01-db558277a2aa.png)

The specified varistor has these properties.

 ![MOV-10D561K](https://user-images.githubusercontent.com/79789422/210129770-4214fd49-b54e-46cc-993d-fee961c1f56b.png)

Thanks for reviewing.

**Comment by srwi** [comment]
Hi @jns-r and sorry for the late reply. Very cool to see someone assembling the PCB! It looks like you are totally correct and I missed that when considering the right parts. I updated the schematic and links accordingly. Thank you!
